import { REGISTER_CODES, REGISTER_PAIR_CODES } from "./registers";

export const BYTE_MASK = 0xff;
export const REGISTER_CODE_MASK = REGISTER_CODES.A;
export const REGISTER_PAIR_CODE_MASK = REGISTER_PAIR_CODES.SP;
export const REGISTER_CODE_WIDTH = 3;
export const REGISTER_PAIR_CODE_WIDTH = 4;
export const DESTINATION_REGISTER_MASK =
  REGISTER_CODE_MASK << REGISTER_CODE_WIDTH;
export const REGISTER_PAIR_MASK =
  REGISTER_PAIR_CODE_MASK << REGISTER_PAIR_CODE_WIDTH;
export const SOURCE_REGISTER_MASK = REGISTER_CODE_MASK;
export const DESTINATION_REGISTER_OPCODE_MASK =
  ~DESTINATION_REGISTER_MASK & BYTE_MASK;
export const SOURCE_REGISTER_OPCODE_MASK = ~SOURCE_REGISTER_MASK & BYTE_MASK;
export const REGISTER_PAIR_OPCODE_MASK = ~REGISTER_PAIR_MASK & BYTE_MASK;
